from ui.color import azul, amarelo, reset

def format_telegram_info_chat(data):
    chat = data.get("GetChat", {}).get("result", {})
    print(f"{azul}ID                     :{amarelo} {chat.get('id', 'N/A')}")
    print(f"{azul}Tipo                   :{amarelo} {chat.get('type', 'N/A')}")
    print(f"{azul}Título                 :{amarelo} {chat.get('title', 'N/A')}")
    print(f"{azul}Username               :{amarelo} {chat.get('username', 'N/A')}")
    print(f"{azul}Nome                   :{amarelo} {chat.get('first_name', 'N/A')}")
    print(f"{azul}Sobrenome              :{amarelo} {chat.get('last_name', 'N/A')}")
    print(f"{azul}Bio                    :{amarelo} {chat.get('bio', 'N/A')}")
    print(f"{azul}Descrição              :{amarelo} {chat.get('description', 'N/A')}")
    print(f"{azul}Convite                :{amarelo} {chat.get('invite_link', 'N/A')}")
    print(f"{azul}Sticker Set            :{amarelo} {chat.get('sticker_set_name', 'N/A')}")
    print(f"{azul}Mensagens Protegidas   :{amarelo} {chat.get('has_protected_content', 'N/A')}")
    print(f"{azul}Fórum                  :{amarelo} {chat.get('is_forum', 'N/A')}")
    admins = data.get("getChatAdministrators", {}).get("result", [])
    for i, admin in enumerate(admins, 1):
        usuario = admin.get("user", {})
        print(f"\n{azul}Administrador          :{amarelo} {i}")
        print(f"{azul}ID                     :{amarelo} {usuario.get('id', 'N/A')}")
        print(f"{azul}Nome                   :{amarelo} {usuario.get('first_name', 'N/A')}")
        print(f"{azul}Sobrenome              :{amarelo} {usuario.get('last_name', 'N/A')}")
        print(f"{azul}Username               :{amarelo} {usuario.get('username', 'N/A')}")
        print(f"{azul}É Bot                  :{amarelo} {usuario.get('is_bot', 'N/A')}")
        print(f"{azul}Status                 :{amarelo} {admin.get('status', 'N/A')}")
    membro = data.get("getChatMember", {}).get("result", {})
    usuario = membro.get("user", {})
    print(f"\n{azul}ID                     :{amarelo} {usuario.get('id', 'N/A')}")
    print(f"{azul}Nome                   :{amarelo} {usuario.get('first_name', 'N/A')}")
    print(f"{azul}Sobrenome              :{amarelo} {usuario.get('last_name', 'N/A')}")
    print(f"{azul}Username               :{amarelo} {usuario.get('username', 'N/A')}")
    print(f"{azul}É Bot                  :{amarelo} {usuario.get('is_bot', 'N/A')}")
    print(f"{azul}Idioma                 :{amarelo} {usuario.get('language_code', 'N/A')}")
    print(f"{azul}Status                 :{amarelo} {membro.get('status', 'N/A')}")
    print(f"{azul}Anônimo                :{amarelo} {membro.get('is_anonymous', 'N/A')}")
    print(f"{azul}Gerenciar Chat         :{amarelo} {membro.get('can_manage_chat', 'N/A')}")
    print(f"{azul}Excluir Mensagens      :{amarelo} {membro.get('can_delete_messages', 'N/A')}")
    print(f"{azul}Convidar Usuários      :{amarelo} {membro.get('can_invite_users', 'N/A')}")
    print(f"{azul}Fixar Mensagens        :{amarelo} {membro.get('can_pin_messages', 'N/A')}")
    print(f"{azul}Restringir Membros     :{amarelo} {membro.get('can_restrict_members', 'N/A')}")
    print(f"{azul}Promover Membros       :{amarelo} {membro.get('can_promote_members', 'N/A')}")
    membros = data.get("getChatMemberCount", {}).get("result", "N/A")
    print(f"{azul}Quantidade de Membros  :{amarelo} {membros}")
def format_telegram_info_bot(data):
    bot = data.get("GetMe", {}).get("result", {})
    print(f"{azul}ID                     :{amarelo} {bot.get('id', 'N/A')}")
    print(f"{azul}É Bot                  :{amarelo} {bot.get('is_bot', 'N/A')}")
    print(f"{azul}Nome                   :{amarelo} {bot.get('first_name', 'N/A')}")
    print(f"{azul}Sobrenome              :{amarelo} {bot.get('last_name', 'N/A')}")
    print(f"{azul}Username               :{amarelo} {bot.get('username', 'N/A')}")
    print(f"{azul}Idioma                 :{amarelo} {bot.get('language_code', 'N/A')}")
    print(f"{azul}Pode entrar em grupos  :{amarelo} {bot.get('can_join_groups', 'N/A')}")
    print(f"{azul}Lê todas mensagens     :{amarelo} {bot.get('can_read_all_group_messages', 'N/A')}")
    print(f"{azul}Suporta Inline         :{amarelo} {bot.get('supports_inline_queries', 'N/A')}")
    print(f"{azul}Business              :{amarelo} {bot.get('can_connect_to_business', 'N/A')}")
    print(f"{azul}Web App               :{amarelo} {bot.get('has_main_web_app', 'N/A')}")
    print(f"{azul}Premium               :{amarelo} {bot.get('is_premium', 'N/A')}")
    webhook = data.get("getWebhookInfo", {}).get("result", {})
    print(f"{azul}URL                    :{amarelo} {webhook.get('url', 'N/A')}")
    print(f"{azul}Certificado            :{amarelo} {webhook.get('has_custom_certificate', 'N/A')}")
    print(f"{azul}Pendentes              :{amarelo} {webhook.get('pending_update_count', 'N/A')}")
    print(f"{azul}IP                     :{amarelo} {webhook.get('ip_address', 'N/A')}")
    print(f"{azul}Último erro            :{amarelo} {webhook.get('last_error_message', 'N/A')}")
    print(f"{azul}Data último erro       :{amarelo} {webhook.get('last_error_date', 'N/A')}")
    print(f"{azul}Máx. conexões          :{amarelo} {webhook.get('max_connections', 'N/A')}")
    print(f"{azul}Atualizações           :{amarelo} {webhook.get('allowed_updates', 'N/A')}")
    nome = data.get("getMyName", {}).get("result", {})
    print(f"{azul}Nome                   :{amarelo} {nome.get('name', 'N/A')}")
    descricao = data.get("getMyDescription", {}).get("result", {})
    print(f"{azul}Descrição              :{amarelo} {descricao.get('description', 'N/A')}")
    curta = data.get("getMyShortDescription", {}).get("result", {})
    print(f"{azul}Descrição Curta        :{amarelo} {curta.get('short_description', 'N/A')}")
    comandos = data.get("getMyCommands", {}).get("result", [])
    if comandos:
        for i, cmd in enumerate(comandos, 1):
            print(f"{azul}Comando {i}            :{amarelo} {cmd.get('command', 'N/A')}")
            print(f"{azul}Descrição              :{amarelo} {cmd.get('description', 'N/A')}")
    else:
        print("sem comandos")
    updates = data.get("getUpdates", {}).get("result", [])
    if updates:
        for i, update in enumerate(updates, 1):
            print(f"{azul}Update ID              :{amarelo} {update.get('update_id', 'N/A')}")
            mensagem = update.get("message", {})
            if mensagem:
                print(f"{azul}Mensagem ID            :{amarelo} {mensagem.get('message_id', 'N/A')}")
                print(f"{azul}Texto                  :{amarelo} {mensagem.get('text', 'N/A')}")
                usuario = mensagem.get("from", {})
                print(f"{azul}Usuário                :{amarelo} {usuario.get('first_name', 'N/A')}")
                print(f"{azul}Username               :{amarelo} {usuario.get('username', 'N/A')}")
                print(f"{azul}ID Usuário             :{amarelo} {usuario.get('id', 'N/A')}")
                chat = mensagem.get("chat", {})
                print(f"{azul}Chat ID                :{amarelo} {chat.get('id', 'N/A')}")
                print(f"{azul}Tipo Chat              :{amarelo} {chat.get('type', 'N/A')}")
    else:
        print(f"{amarelo}Nenhuma atualização encontrada.")
def format_cepaberto(data):
    print(f"{azul}CEP          :{amarelo} {data.get('cep', 'N/A')}")
    print(f"{azul}Logradouro   :{amarelo} {data.get('logradouro', 'N/A')}")
    print(f"{azul}Complemento  :{amarelo} {data.get('complemento', 'N/A')}")
    print(f"{azul}Bairro       :{amarelo} {data.get('bairro', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('cidade', {}).get('nome', 'N/A')}")
    print(f"{azul}UF           :{amarelo} {data.get('estado', {}).get('sigla', 'N/A')}")
    print(f"{azul}DDD          :{amarelo} {data.get('cidade', {}).get('ddd', 'N/A')}")
    print(f"{azul}Latitude     :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude    :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Altitude     :{amarelo} {data.get('altitude', 'N/A')}")
    
def format_apicep(data):
    print(f"{azul}Status       :{amarelo} {data.get('status', 'N/A')}")
    print(f"{azul}CEP          :{amarelo} {data.get('code', 'N/A')}")
    print(f"{azul}Logradouro   :{amarelo} {data.get('address', 'N/A')}")
    print(f"{azul}Bairro       :{amarelo} {data.get('district', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}UF           :{amarelo} {data.get('state', 'N/A')}")
    
def format_brasilapi(data):
    print(f"{azul}CEP          :{amarelo} {data.get('cep', 'N/A')}")
    print(f"{azul}Logradouro   :{amarelo} {data.get('street', 'N/A')}")
    print(f"{azul}Bairro       :{amarelo} {data.get('neighborhood', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}Estado (UF)  :{amarelo} {data.get('state', 'N/A')}")
    print(f"{azul}Provedor     :{amarelo} {data.get('service', 'N/A')}")
    
def format_viacep(data):
    print(f"{azul}CEP          :{amarelo} {data.get('cep', 'N/A')}")
    print(f"{azul}Logradouro   :{amarelo} {data.get('logradouro', 'N/A')}")
    print(f"{azul}Complemento  :{amarelo} {data.get('complemento', 'N/A')}")
    print(f"{azul}Unidade      :{amarelo} {data.get('unidade', 'N/A')}")
    print(f"{azul}Bairro       :{amarelo} {data.get('bairro', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('localidade', 'N/A')}")
    print(f"{azul}UF           :{amarelo} {data.get('uf', 'N/A')}")
    print(f"{azul}Estado       :{amarelo} {data.get('estado', 'N/A')}")
    print(f"{azul}Região       :{amarelo} {data.get('regiao', 'N/A')}")
    print(f"{azul}IBGE         :{amarelo} {data.get('ibge', 'N/A')}")
    print(f"{azul}GIA          :{amarelo} {data.get('gia', 'N/A')}")
    print(f"{azul}DDD          :{amarelo} {data.get('ddd', 'N/A')}")
    print(f"{azul}SIAFI        :{amarelo} {data.get('siafi', 'N/A')}") 
    
def format_ipwhois(data):
    print(f"{azul}Sucesso      :{amarelo} {data.get('success', 'N/A')}")
    print(f"{azul}Mensagem     :{amarelo} {data.get('message', 'N/A')}")
    print(f"{azul}IP           :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Tipo         :{amarelo} {data.get('type', 'N/A')}")
    print(f"{azul}Bogon        :{amarelo} {data.get('bogon', 'N/A')}")
    print(f"{azul}Continente   :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}Cod. Cont.   :{amarelo} {data.get('continent_code', 'N/A')}")
    print(f"{azul}País         :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Cod. País    :{amarelo} {data.get('country_code', 'N/A')}")
    print(f"{azul}Região       :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cod. Região  :{amarelo} {data.get('region_code', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP          :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Latitude     :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude    :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Capital      :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Código Tel.  :{amarelo} {data.get('calling_code', 'N/A')}")
    print(f"{azul}Fronteiras   :{amarelo} {data.get('borders', 'N/A')}")
    flag = data.get("flag", {})
    print(f"{azul}Emoji        :{amarelo} {flag.get('emoji', 'N/A')}")
    print(f"{azul}Unicode      :{amarelo} {flag.get('unicode', 'N/A')}")
    print(f"{azul}Bandeira URL :{amarelo} {flag.get('img', 'N/A')}")
    conn = data.get("connection", {})
    print(f"{azul}ASN          :{amarelo} {conn.get('asn', 'N/A')}")
    print(f"{azul}ISP          :{amarelo} {conn.get('isp', 'N/A')}")
    print(f"{azul}Organização  :{amarelo} {conn.get('org', 'N/A')}")
    print(f"{azul}Domínio      :{amarelo} {conn.get('domain', 'N/A')}")
    print(f"{azul}Rota         :{amarelo} {conn.get('route', 'N/A')}")
    print(f"{azul}Tipo Conexão :{amarelo} {conn.get('type', 'N/A')}")
    tz = data.get("timezone", {})
    print(f"{azul}Timezone     :{amarelo} {tz.get('id', 'N/A')}")
    print(f"{azul}Abrev. TZ    :{amarelo} {tz.get('abbr', 'N/A')}")
    print(f"{azul}DST          :{amarelo} {tz.get('is_dst', 'N/A')}")
    print(f"{azul}Offset       :{amarelo} {tz.get('offset', 'N/A')}")
    print(f"{azul}UTC          :{amarelo} {tz.get('utc', 'N/A')}")
    print(f"{azul}Hora Local   :{amarelo} {tz.get('current_time', 'N/A')}")
    cur = data.get("currency", {})
    print(f"{azul}Moeda        :{amarelo} {cur.get('name', 'N/A')}")
    print(f"{azul}Cod. Moeda   :{amarelo} {cur.get('code', 'N/A')}")
    print(f"{azul}Símbolo      :{amarelo} {cur.get('symbol', 'N/A')}")
    print(f"{azul}Plural       :{amarelo} {cur.get('plural', 'N/A')}")
    print(f"{azul}Nativo       :{amarelo} {cur.get('native', 'N/A')}")
    
def format_ip_api(data):
    print(f"{azul}IP         :{amarelo} {data.get('query', 'N/A')}")
    print(f"{azul}Status     :{amarelo} {data.get('status', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zip', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('lat', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('lon', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ISP        :{amarelo} {data.get('isp', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('as', 'N/A')}{reset}")
    
def format_ipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Rede       :{amarelo} {data.get('network', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} {data.get('version', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country_name', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('country_capital', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}UTC        :{amarelo} {data.get('utc_offset', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('country_calling_code', 'N/A')}")
    print(f"{azul}Moeda      :{amarelo} {data.get('currency_name', 'N/A')} ({data.get('currency', 'N/A')})")
    print(f"{azul}Idiomas    :{amarelo} {data.get('languages', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}{reset}")

def format_ipinfo(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Hostname   :{amarelo} {data.get('hostname', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Localização:{amarelo} {data.get('loc', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ASN / Org  :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}Anycast    :{amarelo} {data.get('anycast', 'N/A')}")

def format_freeipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ipAddress', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} IPv{data.get('ipVersion', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('countryName', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('cityName', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zipCode', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Continente :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('asnOrganization', 'N/A')}")
    print(f"{azul}Código Tel.:{amarelo} +{', +'.join(map(str, data.get('phoneCodes', [])))}")
    print(f"{azul}Moedas     :{amarelo} {', '.join(data.get('currencies', []))}")
    print(f"{azul}Idiomas    :{amarelo} {', '.join(data.get('languages', []))}")

    fusos = data.get("timeZones", [])
    if fusos:
        print(f"{azul}Fusos      :")
        for fuso in fusos:
            print(f"  - {amarelo}{fuso}{reset}")

      
