from ui.color import azul, amarelo, reset

def format_ipwhois(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Tipo       :{amarelo} {data.get('type', 'N/A')}")
    print(f"{azul}Continente :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('calling_code', 'N/A')}")
    print(f"{azul}Fronteiras :{amarelo} {data.get('borders', 'N/A')}")
    print(f"{azul}Bandeira   :{amarelo} {data.get('flag', {}).get('emoji', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('connection', {}).get('asn', 'N/A')}")
    print(f"{azul}ISP        :{amarelo} {data.get('connection', {}).get('isp', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('connection', {}).get('org', 'N/A')}")
    print(f"{azul}Domínio    :{amarelo} {data.get('connection', {}).get('domain', 'N/A')}")
    print(f"{qzul}Timezone   :{amarelo} {data.get('timezone', {}).get('id', 'N/A')}")
    print(f"{azul}UTC        :{amarelo} {data.get('timezone', {}).get('utc', 'N/A')}{reset}")
    
def format_ip_api(data):
    print(f"{azul}IP         :{amarelo} {data.get('query', 'N/A')}")
    print(f"{azul}Status     :{amarelo} {data.get('status', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zip', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('lat', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('lon', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ISP        :{amarelo} {data.get('isp', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('as', 'N/A')}{reset}")
    
def format_ipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Rede       :{amarelo} {data.get('network', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} {data.get('version', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country_name', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('country_capital', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}UTC        :{amarelo} {data.get('utc_offset', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('country_calling_code', 'N/A')}")
    print(f"{azul}Moeda      :{amarelo} {data.get('currency_name', 'N/A')} ({data.get('currency', 'N/A')})")
    print(f"{azul}Idiomas    :{amarelo} {data.get('languages', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}{reset}")

def format_ipinfo(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Hostname   :{amarelo} {data.get('hostname', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Localização:{amarelo} {data.get('loc', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ASN / Org  :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}Anycast    :{amarelo} {data.get('anycast', 'N/A')}")

def format_freeipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ipAddress', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} IPv{data.get('ipVersion', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('countryName', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('cityName', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zipCode', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Continente :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('asnOrganization', 'N/A')}")
    print(f"{azul}Código Tel.:{amarelo} +{', +'.join(map(str, data.get('phoneCodes', [])))}")
    print(f"{azul}Moedas     :{amarelo} {', '.join(data.get('currencies', []))}")
    print(f"{azul}Idiomas    :{amarelo} {', '.join(data.get('languages', []))}")

    fusos = data.get("timeZones", [])
    if fusos:
        print(f"{azul}Fusos      :")
        for fuso in fusos:
            print(f"  - {amarelo}{fuso}{reset}")

      
