from ui.color import azul, amarelo, reset


def format_ipwhois(data):
    print(f"{azul}Sucesso      :{amarelo} {data.get('success', 'N/A')}")
    print(f"{azul}Mensagem     :{amarelo} {data.get('message', 'N/A')}")
    print(f"{azul}IP           :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Tipo         :{amarelo} {data.get('type', 'N/A')}")
    print(f"{azul}Bogon        :{amarelo} {data.get('bogon', 'N/A')}")
    print(f"{azul}Continente   :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}Cod. Cont.   :{amarelo} {data.get('continent_code', 'N/A')}")
    print(f"{azul}País         :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Cod. País    :{amarelo} {data.get('country_code', 'N/A')}")
    print(f"{azul}Região       :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cod. Região  :{amarelo} {data.get('region_code', 'N/A')}")
    print(f"{azul}Cidade       :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP          :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Latitude     :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude    :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Capital      :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Código Tel.  :{amarelo} {data.get('calling_code', 'N/A')}")
    print(f"{azul}Fronteiras   :{amarelo} {data.get('borders', 'N/A')}")
    flag = data.get("flag", {})
    print(f"{azul}Emoji        :{amarelo} {flag.get('emoji', 'N/A')}")
    print(f"{azul}Unicode      :{amarelo} {flag.get('unicode', 'N/A')}")
    print(f"{azul}Bandeira URL :{amarelo} {flag.get('img', 'N/A')}")
    conn = data.get("connection", {})
    print(f"{azul}ASN          :{amarelo} {conn.get('asn', 'N/A')}")
    print(f"{azul}ISP          :{amarelo} {conn.get('isp', 'N/A')}")
    print(f"{azul}Organização  :{amarelo} {conn.get('org', 'N/A')}")
    print(f"{azul}Domínio      :{amarelo} {conn.get('domain', 'N/A')}")
    print(f"{azul}Rota         :{amarelo} {conn.get('route', 'N/A')}")
    print(f"{azul}Tipo Conexão :{amarelo} {conn.get('type', 'N/A')}")
    tz = data.get("timezone", {})
    print(f"{azul}Timezone     :{amarelo} {tz.get('id', 'N/A')}")
    print(f"{azul}Abrev. TZ    :{amarelo} {tz.get('abbr', 'N/A')}")
    print(f"{azul}DST          :{amarelo} {tz.get('is_dst', 'N/A')}")
    print(f"{azul}Offset       :{amarelo} {tz.get('offset', 'N/A')}")
    print(f"{azul}UTC          :{amarelo} {tz.get('utc', 'N/A')}")
    print(f"{azul}Hora Local   :{amarelo} {tz.get('current_time', 'N/A')}")
    cur = data.get("currency", {})
    print(f"{azul}Moeda        :{amarelo} {cur.get('name', 'N/A')}")
    print(f"{azul}Cod. Moeda   :{amarelo} {cur.get('code', 'N/A')}")
    print(f"{azul}Símbolo      :{amarelo} {cur.get('symbol', 'N/A')}")
    print(f"{azul}Plural       :{amarelo} {cur.get('plural', 'N/A')}")
    print(f"{azul}Nativo       :{amarelo} {cur.get('native', 'N/A')}")
    
def format_ip_api(data):
    print(f"{azul}IP         :{amarelo} {data.get('query', 'N/A')}")
    print(f"{azul}Status     :{amarelo} {data.get('status', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zip', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('lat', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('lon', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ISP        :{amarelo} {data.get('isp', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('as', 'N/A')}{reset}")
    
def format_ipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Rede       :{amarelo} {data.get('network', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} {data.get('version', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country_name', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('country_capital', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}UTC        :{amarelo} {data.get('utc_offset', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('country_calling_code', 'N/A')}")
    print(f"{azul}Moeda      :{amarelo} {data.get('currency_name', 'N/A')} ({data.get('currency', 'N/A')})")
    print(f"{azul}Idiomas    :{amarelo} {data.get('languages', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('org', 'N/A')}{reset}")

def format_ipinfo(data):
    print(f"{azul}IP         :{amarelo} {data.get('ip', 'N/A')}")
    print(f"{azul}Hostname   :{amarelo} {data.get('hostname', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('country', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('region', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('city', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('postal', 'N/A')}")
    print(f"{azul}Localização:{amarelo} {data.get('loc', 'N/A')}")
    print(f"{azul}Timezone   :{amarelo} {data.get('timezone', 'N/A')}")
    print(f"{azul}ASN / Org  :{amarelo} {data.get('org', 'N/A')}")
    print(f"{azul}Anycast    :{amarelo} {data.get('anycast', 'N/A')}")

def format_freeipapi(data):
    print(f"{azul}IP         :{amarelo} {data.get('ipAddress', 'N/A')}")
    print(f"{azul}Versão     :{amarelo} IPv{data.get('ipVersion', 'N/A')}")
    print(f"{azul}País       :{amarelo} {data.get('countryName', 'N/A')}")
    print(f"{azul}Código     :{amarelo} {data.get('countryCode', 'N/A')}")
    print(f"{azul}Capital    :{amarelo} {data.get('capital', 'N/A')}")
    print(f"{azul}Região     :{amarelo} {data.get('regionName', 'N/A')}")
    print(f"{azul}Cidade     :{amarelo} {data.get('cityName', 'N/A')}")
    print(f"{azul}CEP        :{amarelo} {data.get('zipCode', 'N/A')}")
    print(f"{azul}Latitude   :{amarelo} {data.get('latitude', 'N/A')}")
    print(f"{azul}Longitude  :{amarelo} {data.get('longitude', 'N/A')}")
    print(f"{azul}Continente :{amarelo} {data.get('continent', 'N/A')}")
    print(f"{azul}ASN        :{amarelo} {data.get('asn', 'N/A')}")
    print(f"{azul}Org        :{amarelo} {data.get('asnOrganization', 'N/A')}")
    print(f"{azul}Código Tel.:{amarelo} +{', +'.join(map(str, data.get('phoneCodes', [])))}")
    print(f"{azul}Moedas     :{amarelo} {', '.join(data.get('currencies', []))}")
    print(f"{azul}Idiomas    :{amarelo} {', '.join(data.get('languages', []))}")

    fusos = data.get("timeZones", [])
    if fusos:
        print(f"{azul}Fusos      :")
        for fuso in fusos:
            print(f"  - {amarelo}{fuso}{reset}")

      
