def format_ipwhois(data):
    print(f"IP         : {data.get('ip', 'N/A')}")
    print(f"Tipo       : {data.get('type', 'N/A')}")
    print(f"Continente : {data.get('continent', 'N/A')}")
    print(f"País       : {data.get('country', 'N/A')}")
    print(f"Região     : {data.get('region', 'N/A')}")
    print(f"Cidade     : {data.get('city', 'N/A')}")
    print(f"CEP        : {data.get('postal', 'N/A')}")
    print(f"Capital    : {data.get('capital', 'N/A')}")
    print(f"Latitude   : {data.get('latitude', 'N/A')}")
    print(f"Longitude  : {data.get('longitude', 'N/A')}")
    print(f"Código     : +{data.get('calling_code', 'N/A')}")
    print(f"Fronteiras : {data.get('borders', 'N/A')}")
    print(f"Bandeira   : {data.get('flag', {}).get('emoji', 'N/A')}")
    print(f"ASN        : {data.get('connection', {}).get('asn', 'N/A')}")
    print(f"ISP        : {data.get('connection', {}).get('isp', 'N/A')}")
    print(f"Org        : {data.get('connection', {}).get('org', 'N/A')}")
    print(f"Domínio    : {data.get('connection', {}).get('domain', 'N/A')}")
    print(f"Timezone   : {data.get('timezone', {}).get('id', 'N/A')}")
    print(f"UTC        : {data.get('timezone', {}).get('utc', 'N/A')}")
    
def format_ip_api(data):
    print(f"IP         : {data.get('query', 'N/A')}")
    print(f"Status     : {data.get('status', 'N/A')}")
    print(f"País       : {data.get('country', 'N/A')}")
    print(f"Código     : {data.get('countryCode', 'N/A')}")
    print(f"Região     : {data.get('regionName', 'N/A')}")
    print(f"Cidade     : {data.get('city', 'N/A')}")
    print(f"CEP        : {data.get('zip', 'N/A')}")
    print(f"Latitude   : {data.get('lat', 'N/A')}")
    print(f"Longitude  : {data.get('lon', 'N/A')}")
    print(f"Timezone   : {data.get('timezone', 'N/A')}")
    print(f"ISP        : {data.get('isp', 'N/A')}")
    print(f"Org        : {data.get('org', 'N/A')}")
    print(f"ASN        : {data.get('as', 'N/A')}")
    
def format_ipapi(data):
    print(f"IP         : {data.get('ip', 'N/A')}")
    print(f"Rede       : {data.get('network', 'N/A')}")
    print(f"Versão     : {data.get('version', 'N/A')}")
    print(f"País       : {data.get('country_name', 'N/A')}")
    print(f"Região     : {data.get('region', 'N/A')}")
    print(f"Cidade     : {data.get('city', 'N/A')}")
    print(f"CEP        : {data.get('postal', 'N/A')}")
    print(f"Capital    : {data.get('country_capital', 'N/A')}")
    print(f"Latitude   : {data.get('latitude', 'N/A')}")
    print(f"Longitude  : {data.get('longitude', 'N/A')}")
    print(f"Timezone   : {data.get('timezone', 'N/A')}")
    print(f"UTC        : {data.get('utc_offset', 'N/A')}")
    print(f"Código     : {data.get('country_calling_code', 'N/A')}")
    print(f"Moeda      : {data.get('currency_name', 'N/A')} ({data.get('currency', 'N/A')})")
    print(f"Idiomas    : {data.get('languages', 'N/A')}")
    print(f"ASN        : {data.get('asn', 'N/A')}")
    print(f"Org        : {data.get('org', 'N/A')}")

def format_ipinfo(data):
    print(f"IP         : {data.get('ip', 'N/A')}")
    print(f"Hostname   : {data.get('hostname', 'N/A')}")
    print(f"País       : {data.get('country', 'N/A')}")
    print(f"Região     : {data.get('region', 'N/A')}")
    print(f"Cidade     : {data.get('city', 'N/A')}")
    print(f"CEP        : {data.get('postal', 'N/A')}")
    print(f"Localização: {data.get('loc', 'N/A')}")
    print(f"Timezone   : {data.get('timezone', 'N/A')}")
    print(f"ASN / Org  : {data.get('org', 'N/A')}")
    print(f"Anycast    : {data.get('anycast', 'N/A')}")

def format_freeipapi(data):
    print(f"IP         : {data.get('ipAddress', 'N/A')}")
    print(f"Versão     : IPv{data.get('ipVersion', 'N/A')}")
    print(f"País       : {data.get('countryName', 'N/A')}")
    print(f"Código     : {data.get('countryCode', 'N/A')}")
    print(f"Capital    : {data.get('capital', 'N/A')}")
    print(f"Região     : {data.get('regionName', 'N/A')}")
    print(f"Cidade     : {data.get('cityName', 'N/A')}")
    print(f"CEP        : {data.get('zipCode', 'N/A')}")
    print(f"Latitude   : {data.get('latitude', 'N/A')}")
    print(f"Longitude  : {data.get('longitude', 'N/A')}")
    print(f"Continente : {data.get('continent', 'N/A')}")
    print(f"ASN        : {data.get('asn', 'N/A')}")
    print(f"Org        : {data.get('asnOrganization', 'N/A')}")
    print(f"Código Tel.: +{', +'.join(map(str, data.get('phoneCodes', [])))}")
    print(f"Moedas     : {', '.join(data.get('currencies', []))}")
    print(f"Idiomas    : {', '.join(data.get('languages', []))}")

    fusos = data.get("timeZones", [])
    if fusos:
        print("Fusos      :")
        for fuso in fusos:
            print(f"  - {fuso}")

      
